pull_request_rules:
  - name: Automatic merge on Crowdin
    conditions:
      - and:
          - author=Ghost-chu
          - title=New Crowdin updates
    actions:
      merge:
        method: squash
        commit_message_template: "[ci skip] Automatically merge Crowdin translations"
